### ISSUE TITLE
Add hard limit of unnapproved submissions per e-mail

### ISSUE THREAD

**Issue by josepostiga** [laravel-portugal/api#17]
Currently, there's no hard limit to how many Link resource submission a given e-mail can do. This makes room for the possibility of a given email to spam our system with unnecessary and unwanted submissions.

We need to avoid that situation.

## Definition of Done

Add a check upon a Link submission that uses the given `user_email` property and avoids that more than 5 unapproved Link resources are submitted, associated with that e-mail address.

**Comment by tiago-sb** [comment]
Hi @josepostiga.

Is this still needed? 
Asking cause it's opened since march...but if so, I'll give it a go!

**Comment by josepostiga** [comment]
Hi @tiago-sb. Yes, this is still a nice enhancement to add to the project.

**Comment by tiago-sb** [comment]
Couple of questions:

1. In the DoD you mention `user_email` - do you mean `author_email` from `Link` class?
2. Do you have a definition for the response to be sent when this limit is exceeded?
Maybe HTTP 429 ?
... any payload?

**Comment by tiago-sb** [comment]
PR #21 opened.
Throwing an error on "Store test coverage report" but I don't think it is related to any change I made.....or is it ??

**Comment by josepostiga** [comment]
> Couple of questions:
> 
> 1. In the DoD you mention `user_email` - do you mean `author_email` from `Link` class?
> 2. Do you have a definition for the response to be sent when this limit is exceeded?
>    Maybe HTTP 429 ?
>    ... any payload?

I noticed that you've already opened the PR, and this for that. I'll just leave the answers to your questions, anyway:
1. Yes, I do. Sorry for the confusion.
2. Yes, I think HTTP status code 429 is a nice one to use here.
