### ISSUE TITLE
A guest should be able to create an account

### ISSUE THREAD

**Issue by josepostiga** [laravel-portugal/api#22]
**Scenario**

Given I'm a guest user
When I submit the required personal information
I expect that account to be created and a confirmation e-mail is sent to the registered e-mail address

Given I'm a guest user
When I click the verification link sent to my e-mail address
I expect my email to be marked as verified (`email_verified_at` property)

**Description**

User accounts will be used to optimize the links submission process since a validated User will be trusted to submit relevant, valid, links for the community, thus relieving the need for reviewing every link they submit to the system. 

By default, a user should still be bound to the current unverified article max validation, unless their account gets verified, to which case all limitations are lifted and an infinite number of resources can be submitted through their account. This verified status can be reverted at any time.

**Database and schema information**

A new `user` table needs to be created with the following structure:
- `id`: PK;
- `name`: string, not null, indexed;
- `email`: string, not null, unique;
- `password`: string, not null;
- `trusted`: boolean, not null, default to false;
- `email_verified_at`: timestamp with timezone, nullable;
- `created_at`: timestamp with timezone, nullable, default to creation timestamp;
- `updated_at`: timestamp with timezone, nullable, default to creation timestamp;
- `deleted_at`: timestamp with timezone, nullable.

**Notes** 
* All not nullable columns must be validated before being persisted.
* The `trusted` column is the marker that sets the user to not have any limitations to resource creation.
* The `email_verified_at` column is used to check that it's a real user, and is set to true after a verification notification is sent to the registered email address and the receiver clicks in the verification link.
* The `deleted_at` column is for soft-deletions.

**Comment by jorgercosta** [comment]
What's the workflow for account verification?
Can a verified user verify other accounts?
Maybe change the field name to "trusted"?

**Comment by josepostiga** [comment]
@jorgercosta:
1. When the user submits for an account, it must receive a confirmation e-mail with a link that, after being clicked on, should update the `email_verified_at` column with the current timestamp.
2. No. On another issue, we'll add account types to users and at that time we'll allow certain account types to verify users.
3. Sure, no problem in using that name for that column.

I've updated the issue to reflect these decisions.

**Comment by tiagof** [comment]
I'll try to do this one. (how to update to "in progress" in the project?)

**Comment by josepostiga** [comment]
@tiagof you can create a draft pull-request referencing this issue. It'll both trigger the board automation to move the issue to the "In Progress" state, and let people know this issue is already being solved.

Happy coding :+1:

**Comment by tiagof** [comment]
Thanks.
Created the draft PR (hope I did right :))

**Comment by josepostiga** [comment]
Contrary to what it says in the automation of the board, looks like it doesn't work with drft PRs. Sorry for the confusion. I'll update things manually, but the workflow is ok.
