### ISSUE TITLE
Add account types and permissions to registered users account

### ISSUE THREAD

**Issue by josepostiga** [laravel-portugal/api#24]
**Is your feature request related to a problem? Please describe.**
Users' accounts should have an account type marker related to the access permission they have on the API. This new property defines what actions they can execute.

**Describe the solution you'd like**
We need to add a new column to the `users` table (I propose `account_type`) as an enum (user, editor, admin), not nullable, with a default of `user`.

The permissions matrix should be as follow:
* `user`: the same type of access and permissions we currently have. It can submit links with the configured max limit of unapproved resources policy (or not, if the `trusted` property is active).
* `editor`: can submit links without any limit on unapproved resources, can list, view, update, delete, or approve other user-submitted links as long as those users' account type is `user`. Besides, it allows the list and view all details of users of type `user`, and can update the `trusted` property of those accessible users.
* `admin`: can pretty much do anything, access anything, and manage everything.

**Describe alternatives you've considered**
The current alternative is to make this management directly on the database, which is not ideal to be given access to every editor/admin of the system. 

**Additional context**
This builds on the features of #22, which introduces users' accounts.

**Comment by tiagof** [comment]
I'll take this one.
