### ISSUE TITLE
An authenticated user can post a question

### ISSUE THREAD

**Issue by josepostiga** [laravel-portugal/api#25]
**Scenario**

Given I'm an authenticated user of any type
When I send a POST request to /discussions/questions with the required input
I expect that question to be stored

**Description**

One of the main objectives of the Laravel-Portugal community is to help our fellow developers overcome their difficulties and have their doubts answered by other developers. This type of interaction has been supported by the normal operations of our Discord server, which has specific channels where registered members can post questions and start discussing them.

However, when many developers start to submit any questions, at the same time, the conversation gets to an unbearable and unmanageable point that to avoid such a mess, many people start to move the discussion to private chats and won't benefit other devs with the same doubts because it's unsearchable.

Since we're developing a new portal, and we've planned to introduce [users' accounts](https://github.com/laravel-portugal/api/issues/22), it's time to start adding the possibility to concentrate all questions, and the knowledge shared while resolving them, in a publicly available place. It's also a good way to focus the Discord server to only be a place of synchronous, real-time, conversations.

**Database and schema information**

A new `questions` table should be created with the following structure:
- `id`: PK.
- `author_id`: FK, related to the user who created the question. Must be required and indexed.
- `title`: the title of the question. Must be required and indexed.
- `slug`: the URL friendly identifier, automatically generated based on the title.
- `description`: the question itself. Must be required.
- `created_at`: timestamp with timezone. Must be indexed and default to the date the resource is created.
- `updated_at`: timestamp with timezone. Must be indexed.
- `deleted_at`: timestamp with timezone. Must be indexed and default to null. This indicates if the resource was deleted.
- `resolved_at`: timestamp with timezone. Must be indexed and default to null. This indicates that the question as resolved.

**Additional requirements**

This builds on the features of #22, which introduces users' accounts.

**Comment by tiagof** [comment]
Hi @josepostiga I'l pick this one.

**Comment by josepostiga** [comment]
@tiagof as discussed on our Discord server, I've updated the proposed database table schema.

**Comment by tiagof** [comment]
PR is ready for review.
Please note that the routes "style" doesn't match what you recently applied in Account with this [commit](https://github.com/laravel-portugal/api/commit/9f9aa744dcce877365c664b5de0ab8e0e2a2e2d7) - i.e., defining the prefix in the XXXServiceProvider.

To keep the same logic we should change the requirement and move the endpoint `/questions` to `/discussions/questions` having `discussions` as prefix for all the routes from this domain.
Let me know if I should change it.

**Comment by josepostiga** [comment]
@tiagof that proposal, of adding the `/discussions` prefix, looks really good to me. In fact I think we can encapsulate the `questions` domain inside a new `discussions` domain.
