### ISSUE TITLE
A guest or an authenticated user can list questions

### ISSUE THREAD

**Issue by josepostiga** [laravel-portugal/api#26]
**Scenario**

Given I'm a guest or an authenticated user of any type
When I send a GET request to /discussions/questions
I expect to receive a list of paginated, non-deleted, questions resources (15 per page)

Given I'm a guest or an authenticated user of any type
When I send a GET request to /discussions/questions with any searchable properties
I expect to receive a list of paginated, non-deleted, questions resources that match the query param (15 per page)

Given I'm a guest user
When I send more than 30 GET requests to /discussions/questions within a single minute
I expect to receive a 429 Too Many Requests status code until the next minute

**Searchable properties**
- `author_id`: mapped to an `author` query param (`?author={id}`).
- `title`: mapped to a `title` query param (`?title={search-text}`).
- `created_at`: mapped to a `created[]` period type query param (`?created[from]={start-period}&created[to]={end-period}`).
- `resolved_at`: mapped to a `resolved` query param (`?resolved=true`).

**Additional requirements**

The list should be ordered from the most recent resources to the eldest.

This builds on the features of #25, which introduces the storage of questions resources.

**Comment by dleicam** [comment]
Can i pick this one?
