### ISSUE TITLE
Update timestamps columns of links table to consider timezones 

### ISSUE THREAD

**Issue by josepostiga** [laravel-portugal/api#28]
**Is your feature request related to a problem? Please describe.**
Current links table schema has timestamps columns without timezone information. Timezones are a valid concern, especially when it's expected to have resources submitted by users from different timezones.

Since we're preparing the application to support users' accounts (see #22), we should add this information now and handle timezone differences directly on the database layer.

**Describe the solution you'd like**
Add the necessary migrations to update all timestamp columns to contain timezone information. Besides that, ensure that the application layer always calculates any timezone information to always be stored and shown as UTC. The clients, whenever possible, should deal with any timezone calculation for a given guest or user.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by adevr** [comment]
This issue is directly related with #29 !
