### ISSUE TITLE
Update timestamps columns of tags table to consider timezones

### ISSUE THREAD

**Issue by josepostiga** [laravel-portugal/api#29]
**Is your feature request related to a problem? Please describe.**
The current tags table schema has timestamps columns without timezone information. Timezones are a valid concern, especially when it's expected to have resources submitted by users from different timezones.

Since we're preparing the application to support users' accounts (see #22), we should add this information now and handle timezone differences directly on the database layer.

**Describe the solution you'd like**
Add the necessary migrations to update all timestamp columns to contain timezone information. Besides that, ensure that the application layer always calculates any timezone information to always be stored and shown as UTC. The clients, whenever possible, should deal with any timezone calculation for a given guest or user.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by adevr** [comment]
Hello @josepostiga !

To start my contribution I could update this issue and this (#28) one too.

I was thinking about altering the tables, removing the standard timestamps columns and creating the timestampsTz ones.
I read about that in some articles and I believe that this is the best way to improve this.. 

Let me know if you have other suggestions for both issues! 😄

**Comment by josepostiga** [comment]
@adevr sure! Feel free to start working on that. Just open a draft PR to link both issues.

I'll go ahead and update the assignee, too.

**Comment by adevr** [comment]
@josepostiga sure! I will comment that issue as well!
