### ISSUE TITLE
An authenticated user can delete a question

### ISSUE THREAD

**Issue by josepostiga** [laravel-portugal/api#30]
**Scenario**

Given I'm an authenticated user of any type
When I send a DELETE request to /discussions/questions/{questionId} and the question was created by me
I expect that question to be soft-deleted

Given I'm an authenticated user of type admin
When I send a DELETE request to /discussions/questions/{questionId}
I expect that question to be soft-deleted

**Additional requirements**

This builds on the features of #25.

**Comment by tiagof** [comment]
Hi @josepostiga I'll take this one together with #27
