### ISSUE TITLE
An authenticated user can post an answer to a question

### ISSUE THREAD

**Issue by josepostiga** [laravel-portugal/api#31]
**Scenario**

Given I'm an authenticated user of any type
When I send a POST request to /discussions/questions/{questionId}/answers with the required input
I expect that answer to the given question to be stored

**Database and schema information**

A new `question_answers` table should be created with the following structure:
- `id`: PK.
- `question_id`: the related question internal identifier. Must be required and indexed.
- `author_id`: FK, related to the user who created the answer. Must be required and indexed.
- `content`: the answer itself. Must be required.
- `created_at`: timestamp with timezone. Must be indexed and default to the date the resource is created.
- `updated_at`: timestamp with timezone. Must be indexed.
- `deleted_at`: timestamp with timezone. Must be indexed and default to null. This indicates if the resource was deleted.

**Additional requirements**

This builds on the features of #25, which introduces questions.

**Comment by dleicam** [comment]
If is ok, i pick this one.

**Comment by josepostiga** [comment]
@dleicam this issue required #25 to be integrated. The related PR is expected to be reviewed between today and tomorrow, but it can take some time to actually get merged (depends on if it might need additional work).

If you don't mind waiting, we're totally ok with you taking this one. If you don't want to wait, then you can choose another issue :smiley:

**Comment by dleicam** [comment]
Thanks @josepostiga , i'm waiting for the merge of issue #25
