### ISSUE TITLE
A guest or an authenticated user can list answers of a question

### ISSUE THREAD

**Issue by josepostiga** [laravel-portugal/api#32]
**Scenario**

Given I'm a guest or an authenticated user of any type
When I send a GET request to /discussions/questions/{questionId}/answers
I expect to receive a list of paginated, non-deleted, answers resources (15 per page)

Given I'm a guest or an authenticated user of any type
When I send a GET request to /discussions/questions/{questionId}/answers with any searchable properties
I expect to receive a list of paginated, non-deleted, answers resources that match the query param (15 per page)

Given I'm a guest user
When I send more than 30 GET requests to /discussions/questions/{questionId}/answers within a single minute
I expect to receive a 429 Too Many Requests status code until the next minute

**Searchable properties**
- `author_id`: mapped to an `author` query param (`?author={id}`).
- `created_at`: mapped to a `created[]` period type query param (`?created[from]={start-period}&created[to]={end-period}`).

**Additional requirements**

The list should be ordered from the most recent resources to the eldest.

This builds on the features of #25, which introduces the storage of questions resources.

**Comment by ana-lisboa** [comment]
I want to do this one when the dependencies are ready :)

**Comment by tiagof** [comment]
@ana-lisboa I think all dependencies are ready :)

**Comment by ana-lisboa** [comment]
I've started developing already ;)

Cumprimentos,
Ana Lisboa

A segunda, 26/10/2020, 10:08, Tiago Fernandes <notifications@github.com>
escreveu:
