### ISSUE TITLE
An authenticated user can update an answer of a given question

### ISSUE THREAD

**Issue by josepostiga** [laravel-portugal/api#33]
**Scenario**

Given I'm an authenticated user of any type
When I send a PATCH request to /discussions/questions/{questionId}/answers/{answerId} with the updatable input and the answer was created by me
I expect that answer to be updated

Given I'm an authenticated user of any type
When I send a PATCH request to /discussions/questions/{questionId}/answers/{answerId} with the updatable input and the answer was not created by me
I expect to not be able to update that answer

**Updatable input**

- `content`: the answer itself.
- `updated_at`: timestamp with timezone. Must be automatically updated with the current timestamp of the update action.

**Additional requirements**

This builds on the features of #31.

**Comment by ana-lisboa** [comment]
I wanto to do this one, when the dependencies are ready ;)

**Comment by adevr** [comment]
I can take care of this issue as soon as soon as the dependencies are resolved! 🔜

**Comment by tiagof** [comment]
@adevr I think all dependencies are ready. :)

**Comment by adevr** [comment]
@tiagof I know! I will be working on this soon.

**Comment by tiagof** [comment]
@josepostiga would it make since to shorten 
`/discussions/questions/{questionId}/answers/{answerId}`
to
`/discussions/answers/{answerId}`
since the `question_id` is unnecessary given we provide the `answer_id` and that is unique?

**Comment by josepostiga** [comment]
@tiagof although it's not really necessary, it's contextually relevant.
