### ISSUE TITLE
A guest should be able to login and logout

### ISSUE THREAD

**Issue by josepostiga** [laravel-portugal/api#37]
**Scenario**

Given I'm a guest and have a registered account
When I send a POST request to /accounts/login with valid credentials
I expect to create a personal access token assigned to the device I'm login in from

Given I'm a guest and have a registered account
When I send a POST request to /accounts/login with invalid credentials
I expect to not be able to log in

Given I'm a guest
When I send more than 10 POST requests to /accounts/login with invalid credentials in the same minute
I expect to be blocked from doing more requests until the next minute (throttled)

Given I'm an authenticated user
When I send a GET request to /accounts/me
I expect to access my account information

Given I'm an authenticated user
When I send a POST request to /accounts/logout
I expect to revoke the used token

**Description**

With the implementation of #22, we now need to support authentication to allow users to have access to a personal access token that gives them access to their account's information as well as other protected resources in the application that requires a registered account.

**Additional requirements**

~~We should consider use [Passport](https://laravel.com/docs/8.x/passport) for this. It may come with a lot more than we need but the alternative of rolling out our own authentication system isn't ideal. Unfortunately, AFAIK, Sanctum isn't supported on Lumen.~~  :man_shrugging:

Update: during the development of this issue, we found out that Passport doesn't play well with Lumen, by default. We chose to go with another implementation: https://github.com/tymondesigns/jwt-auth.

**Comment by dleicam** [comment]
I will take this one, ok?

**Comment by josepostiga** [comment]
@dleicam and @tiagof we should probably discuss other approaches to authentication than using Passport. I originally thought that it would be a simple drop-in, but it's turning out to be a hassle to integrate it with Lumen. 

Let's discuss this on our Discord server.

**Comment by josepostiga** [comment]
FYI: I've updated this issue to reflect the current state of development and decisions made.
