### ISSUE TITLE
A guest or an authenticated user can see details of a question

### ISSUE THREAD

**Issue by josepostiga** [laravel-portugal/api#48]
**Scenario**

Given I'm an authenticated user of any type
When I send a GET request to /discussions/questions/{questionId}
I expect to see the details of the given question

Given I'm a guest user
When I send more than 30 GET requests to /discussions/questions/{questionId} within a single minute
I expect to receive a 429 Too Many Requests status code until the next minute

**Additional requirements**

This builds on the features of #25.

**Comment by dleicam** [comment]
Solved with PR #49
