### ISSUE TITLE
Images should be in public folder, and have its full url in Link body

### ISSUE THREAD

**Issue by ijpatricio** [laravel-portugal/api#62]
**Scenario**

Scenario: Access uploaded images
    When an application requests a `Link` and receives it
    Then its `cover_image` (or other attribute) displays the full url for it.

**Description**

We need the full url on the `Link` json body.

**Database and schema information**

No.

**Additional requirements**

Yes, the shown url must be accessible, and right now misses the symlink to be in the public folder.

**Comment by ijpatricio** [comment]
Maybe images could be in a different `laravel disk`? With s3 driver, maybe [minio](https://min.io/) ?

What do you think?
@josepostiga @pedro-vasconcelos

**Comment by tiagof** [comment]
Hi @ijpatricio the api is now storing the cover images in the public folder. This should be enough, right? (See PR #59)

**Comment by ijpatricio** [comment]
Hi @tiagof !!
Yeah, sure. s3 comtapible i just find it more separeted concerns, was just a thought i decided to share....

The issue came up because when running locally, we couldn't figure out how to create the storage symlink to the (really) public folder, programatically

**Comment by tiagof** [comment]
Ah ok. I meant that for the "public" part, it is done. 
Now as for having it on the api host or on s3... I'll leave the decision to @josepostiga, but I'd suggest to keep it simple for now and move it later if it becomes necessary.

**Comment by ijpatricio** [comment]
yeah, sure!

for the public folder, are we supposed to create the symlink manually or what?

**Comment by tiagof** [comment]
How else?! This is not Laravel! 😁

**Comment by ijpatricio** [comment]
Ow, sorry, my mistake, this is not where I parked my car 😛😛😛
Leaving in 3, 2, 1.......

**Comment by josepostiga** [comment]
As @tiagof said, we already have that integrated. As for the symlink part, I've ported the symlink command on 4d9256e864cf3a72a0191f44961fc39f2688cd64
